CREATE SCHEMA IF NOT EXISTS raw_pg;

DROP TABLE IF EXISTS raw_pg.mock_data;

CREATE TABLE IF NOT EXISTS raw_pg.mock_data (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    external_id integer,
    customer_inner_id integer GENERATED ALWAYS AS IDENTITY,
    customer_first_name text,
    customer_last_name text,
    customer_age integer,
    customer_email text,
    customer_country text,
    customer_postal_code text,
    customer_pet_inner_id integer GENERATED ALWAYS AS IDENTITY,
    customer_pet_type text,
    customer_pet_name text,
    customer_pet_breed text,
    seller_inner_id integer GENERATED ALWAYS AS IDENTITY,
    seller_first_name text,
    seller_last_name text,
    seller_email text,
    seller_country text,
    seller_postal_code text,
    product_inner_id integer GENERATED ALWAYS AS IDENTITY,
    product_name text,
    product_category text,
    product_price double precision,
    product_quantity integer,
    sale_date date,
    sale_customer_id integer,
    sale_seller_id integer,
    sale_product_id integer,
    sale_quantity integer,
    sale_total_price double precision,
    store_inner_id integer GENERATED ALWAYS AS IDENTITY,
    store_name text,
    store_location text,
    store_city text,
    store_state text,
    store_country text,
    store_phone text,
    store_email text,
    pet_category text,
    product_weight double precision,
    product_color text,
    product_size text,
    product_brand text,
    product_material text,
    product_description text,
    product_rating double precision,
    product_reviews integer,
    product_release_date date,
    product_expiry_date date,
    supplier_inner_id integer GENERATED ALWAYS AS IDENTITY,
    supplier_name text,
    supplier_contact text,
    supplier_email text,
    supplier_phone text,
    supplier_address text,
    supplier_city text,
    supplier_country text
);

COPY raw_pg.mock_data (
    external_id,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    sale_date,
    sale_customer_id,
    sale_seller_id,
    sale_product_id,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    product_release_date,
    product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
) FROM '/data/MOCK_DATA (5).csv' WITH (FORMAT csv, HEADER true, QUOTE '"', NULL '');

COPY raw_pg.mock_data (
    external_id,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    sale_date,
    sale_customer_id,
    sale_seller_id,
    sale_product_id,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    product_release_date,
    product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
) FROM '/data/MOCK_DATA (6).csv' WITH (FORMAT csv, HEADER true, QUOTE '"', NULL '');

COPY raw_pg.mock_data (
    external_id,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    sale_date,
    sale_customer_id,
    sale_seller_id,
    sale_product_id,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    product_release_date,
    product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
) FROM '/data/MOCK_DATA (7).csv' WITH (FORMAT csv, HEADER true, QUOTE '"', NULL '');

COPY raw_pg.mock_data (
    external_id,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    sale_date,
    sale_customer_id,
    sale_seller_id,
    sale_product_id,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    product_release_date,
    product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
) FROM '/data/MOCK_DATA (8).csv' WITH (FORMAT csv, HEADER true, QUOTE '"', NULL '');

COPY raw_pg.mock_data (
    external_id,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    sale_date,
    sale_customer_id,
    sale_seller_id,
    sale_product_id,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    product_release_date,
    product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
) FROM '/data/MOCK_DATA (9).csv' WITH (FORMAT csv, HEADER true, QUOTE '"', NULL '');
