connector.name=clickhouse
connection-url=jdbc:clickhouse://clickhouse:8123/default
connection-user=etl
connection-password=etl
clickhouse.map-string-as-varchar=true
insert.non-transactional-insert.enabled=true
write.batch-size=10000
