FROM openjdk:24-rc-jdk-slim as BUILD

COPY . /src
WORKDIR /src
RUN ./gradlew --no-daemon shadowJar main

FROM flink:1.20.2-scala_2.12-java11

#RUN wget -P /opt/flink/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.4.0-1.20/flink-sql-connector-kafka-3.4.0-1.20.jar; \
#    wget -P /opt/flink/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jdbc/3.3.0-1.20/flink-connector-jdbc-3.3.0-1.20.jar;

COPY --from=BUILD /src/build/libs/Flink-1.0-SNAPSHOT-all.jar /opt/flink/lib/

RUN chown -R flink:flink /opt/flink/lib
